<?php
/**
 * @file
 * Code for the GSB Feature Faculty Display feature.
 */

include_once 'gsb_feature_faculty_display.features.inc';

/**
 * Implements hook_block_info().
 */
function gsb_feature_faculty_display_block_info() {
  $blocks['az_list'] = array(
    'info' => 'A-Z list for Faculty search.',
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 */
function gsb_feature_faculty_display_block_view($delta = '') {
  if ($delta == 'az_list') {
    drupal_add_js(drupal_get_path('module', 'gsb_feature_faculty_display') . '/js/gsb_feature_faculty_display.js', array('scope' => 'footer'));
    $block['subject'] = '';
    $block['content'] = '<ul class="facet-title-az"><li>' . t('All') . '</li>';
    for ($i = 65; $i <= 90; $i++) {
      $block['content'] .= '<li>';
      $block['content'] .= chr($i);
      $block['content'] .= '</li>';
    }

    $block['content'] .= '</ul>';

    return $block;
  }
}
/**
 * Implements hook_form_FORM_ID_alter() for views_exposed_form().
 */
function gsb_feature_faculty_display_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if ($form_state['view']->name == 'faculty_filters') {
    // Exclude the search text field from auto-submit.
    $form['search']['#attributes']['class'][] = 'ctools-auto-submit-exclude';
  }
}

function gsb_feature_faculty_display_gsb_fpp_customizations_icons_alter(&$icons) {
  $module_path = drupal_get_path('module', 'gsb_feature_faculty_display');
  $icons_settings = array(
    'views_panes:faculty_filters-faculty_by_id_or_tag' => 'faculty-by-id-or-tag.jpg',        
  );
  foreach($icons_settings as $key => $value) {
    if (isset($icons[$key]['icon'])) {
      $icons[$key]['icon'] = $module_path . '/images/' . $value;
    }
  }
}
